#pragma once

#include <stdint.h>

enum {
    ASTRA_SPI_WRITE_OP = 0x57,
    ASTRA_SPI_READ_OP = 0x52,
    ASTRA_SPI_TOKEN_EMPTY = 0x00,
    ASTRA_SPI_TOKEN_DATA = 0x01,
};

enum {
    ASTRA_CMD_IDENTIFY = 0x01,
    ASTRA_CMD_BOOT_STATUS = 0x02,
    ASTRA_CMD_BOOT_BEGIN = 0x10,
    ASTRA_CMD_BOOT_DATA = 0x11,
    ASTRA_CMD_BOOT_COMMIT = 0x12,
    ASTRA_CMD_BOOT_ABORT = 0x13,
    ASTRA_CMD_SERVICE_HELLO = 0x20,
    ASTRA_CMD_BLOCK_POLL = 0x21,
    ASTRA_CMD_BLOCK_PUSH = 0x22,
    ASTRA_CMD_BLOCK_FETCH = 0x23,
    ASTRA_CMD_BLOCK_COMPLETE = 0x24,
    ASTRA_CMD_INPUT_EVENT = 0x30,
};

enum {
    ASTRA_STATUS_OK = 0x00,
    ASTRA_STATUS_BAD_COMMAND = 0x01,
    ASTRA_STATUS_BAD_STATE = 0x02,
    ASTRA_STATUS_BAD_ARGUMENT = 0x03,
    ASTRA_STATUS_OVERFLOW = 0x04,
    ASTRA_STATUS_CRC = 0x05,
    ASTRA_STATUS_SIZE = 0x06,
    ASTRA_STATUS_BUSY = 0x07,
    ASTRA_STATUS_STALE = 0x08,
};

enum {
    ASTRA_BOOT_REQUESTED = 1u << 0,
    ASTRA_BOOT_BUSY = 1u << 1,
    ASTRA_BOOT_DONE = 1u << 2,
    ASTRA_BOOT_ERROR = 1u << 3,
    ASTRA_HOST_SEEN = 1u << 4,
};

enum {
    ASTRA_CAP_BOOT_STREAM = 1u << 0,
    ASTRA_CAP_RAW_BLOCK = 1u << 1,
    ASTRA_CAP_INPUT_EVENTS = 1u << 2,
};

enum {
    ASTRA_STATE_LINK_UP = 1u << 0,
    ASTRA_STATE_MEDIA_PRESENT = 1u << 1,
    ASTRA_STATE_WRITE_ENABLE = 1u << 2,
};

enum {
    ASTRA_BLOCK_READ = 1,
    ASTRA_BLOCK_WRITE = 2,
    ASTRA_BLOCK_FLUSH = 3,
};

enum {
    ASTRA_COMPLETION_OK = 0,
    ASTRA_COMPLETION_IO_ERROR = 1,
    ASTRA_COMPLETION_CRC_ERROR = 2,
    ASTRA_COMPLETION_BAD_REQUEST = 3,
    ASTRA_COMPLETION_TIMEOUT = 4,
    ASTRA_COMPLETION_HOST_RESET = 5,
    ASTRA_COMPLETION_MEDIA_CHANGED = 6,
};

enum {
    ASTRA_INPUT_KEYBOARD = 1,
    ASTRA_INPUT_POINTER = 2,
    ASTRA_INPUT_GAMEPAD = 3,
};

#define ASTRA_HOST_PROTOCOL_MAJOR 1u
#define ASTRA_HOST_PROTOCOL_MINOR 1u
#define ASTRA_BOOT_LOAD_OFFSET 0x01e00000u
#define ASTRA_BOOT_CHUNK_BYTES 256u
#define ASTRA_BLOCK_CHUNK_BYTES 256u
#define ASTRA_BLOCK_SECTOR_BYTES 512u
#define ASTRA_BLOCK_MAX_SECTORS 16u
#define ASTRA_RUNTIME_MAX_PAYLOAD \
    (14u + ASTRA_BLOCK_CHUNK_BYTES)
