#pragma once

#include <stdint.h>

enum {
    ASTRA_SPI_WRITE_OP = 0x57,
    ASTRA_SPI_READ_OP = 0x52,
    ASTRA_SPI_TOKEN_EMPTY = 0x00,
    ASTRA_SPI_TOKEN_DATA = 0x01,
};

enum {
    ASTRA_CMD_IDENTIFY = 0x01,
    ASTRA_CMD_BOOT_STATUS = 0x02,
    ASTRA_CMD_BOOT_BEGIN = 0x10,
    ASTRA_CMD_BOOT_DATA = 0x11,
    ASTRA_CMD_BOOT_COMMIT = 0x12,
    ASTRA_CMD_BOOT_ABORT = 0x13,
};

enum {
    ASTRA_STATUS_OK = 0x00,
    ASTRA_STATUS_BAD_COMMAND = 0x01,
    ASTRA_STATUS_BAD_STATE = 0x02,
    ASTRA_STATUS_BAD_ARGUMENT = 0x03,
    ASTRA_STATUS_OVERFLOW = 0x04,
    ASTRA_STATUS_CRC = 0x05,
    ASTRA_STATUS_SIZE = 0x06,
};

enum {
    ASTRA_BOOT_REQUESTED = 1u << 0,
    ASTRA_BOOT_BUSY = 1u << 1,
    ASTRA_BOOT_DONE = 1u << 2,
    ASTRA_BOOT_ERROR = 1u << 3,
    ASTRA_HOST_SEEN = 1u << 4,
};

enum {
    ASTRA_CAP_BOOT_STREAM = 1u << 0,
};

#define ASTRA_HOST_PROTOCOL_MAJOR 1u
#define ASTRA_HOST_PROTOCOL_MINOR 0u
#define ASTRA_BOOT_LOAD_OFFSET 0x01e00000u
#define ASTRA_BOOT_CHUNK_BYTES 256u
