#!/usr/bin/env python3
"""Compress the ROM-resident images and emit their verification constants.

The kernel and the initial user image shipped raw until the ROM ran short.
Both are now LZ4-legacy streams decoded by the firmware into their load
addresses, which is the same decoder and the same frame format the splash has
always used.

Sizes and CRC-32 values become compile-time constants rather than a container
header: firmware then has nothing to parse before it can validate, and a
payload that disagrees with the ROM it was built with cannot decode silently.
"""

from __future__ import annotations

import argparse
import hashlib
import zlib
from pathlib import Path

from pack_boot_splash import compress_legacy_lz4

GUARD = "ASTRA_ROM_PAYLOADS_H"

ELF_MAGIC = b"\x7fELF"


def debug_sections(image: bytes) -> list[str]:
    """Names of any DWARF sections in a big-endian 32-bit ELF.

    Every m68k object is compiled with -g so a debugger has something to say,
    and nothing that ships is supposed to carry the result: the kernel becomes
    a raw binary and the user image is stripped. This is what makes that a rule
    rather than a habit -- the ROM window is fixed in RTL, and DWARF arriving
    in it would be found as a size failure with no obvious cause.
    """
    if not image.startswith(ELF_MAGIC) or len(image) < 52:
        return []
    if image[4] != 1 or image[5] != 2:  # 32-bit, big-endian
        return []
    section_offset = int.from_bytes(image[32:36], "big")
    entry_size = int.from_bytes(image[46:48], "big")
    count = int.from_bytes(image[48:50], "big")
    names_index = int.from_bytes(image[50:52], "big")
    if section_offset == 0 or count == 0 or names_index >= count:
        return []
    names_header = section_offset + names_index * entry_size
    names_start = int.from_bytes(image[names_header + 16:names_header + 20], "big")
    found = []
    for index in range(count):
        header = section_offset + index * entry_size
        name_offset = int.from_bytes(image[header:header + 4], "big")
        end = image.index(b"\0", names_start + name_offset)
        name = image[names_start + name_offset:end].decode("ascii", "replace")
        if name.startswith(".debug"):
            found.append(name)
    return found


def pack(name: str, source: Path, output: Path) -> dict[str, object]:
    raw = source.read_bytes()
    if not raw:
        raise SystemExit(f"{source}: empty payload")
    carried = debug_sections(raw)
    if carried:
        raise SystemExit(
            f"{source}: carries debug information into the ROM "
            f"({', '.join(carried[:4])}); strip it before packing")
    compressed = compress_legacy_lz4(raw, output)
    return {
        "name": name,
        "source": source,
        "output": output,
        "raw_bytes": len(raw),
        "raw_crc32": zlib.crc32(raw) & 0xFFFFFFFF,
        "compressed_bytes": len(compressed),
        "sha256": hashlib.sha256(compressed).hexdigest(),
    }


def write_header(header: Path, payloads: list[dict[str, object]]) -> None:
    lines = [
        "/* Generated by pack_payload.py. Do not edit. */",
        f"#ifndef {GUARD}",
        f"#define {GUARD}",
        "",
    ]
    for payload in payloads:
        prefix = f"ASTRA_{payload['name']}_PAYLOAD"
        lines += [
            f"#define {prefix}_RAW_BYTES {payload['raw_bytes']}u",
            f"#define {prefix}_RAW_CRC32 0x{payload['raw_crc32']:08x}u",
            f"#define {prefix}_COMPRESSED_BYTES {payload['compressed_bytes']}u",
            "",
        ]
    lines += ["#endif", ""]
    header.parent.mkdir(parents=True, exist_ok=True)
    temporary = header.with_suffix(header.suffix + ".tmp")
    temporary.write_text("\n".join(lines))
    temporary.replace(header)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--payload", action="append", required=True, metavar="NAME=SOURCE=OUTPUT",
        help="payload name, input binary, and compressed output path")
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args()

    payloads = []
    for entry in args.payload:
        fields = entry.split("=")
        if len(fields) != 3:
            raise SystemExit(f"--payload expects NAME=SOURCE=OUTPUT, got {entry!r}")
        name, source, output = fields
        payloads.append(pack(name, Path(source), Path(output)))

    write_header(args.header, payloads)
    for payload in payloads:
        ratio = payload["compressed_bytes"] / payload["raw_bytes"]
        print(
            f"{payload['output']}: {payload['compressed_bytes']} bytes "
            f"({ratio:.2f} of {payload['raw_bytes']}); "
            f"raw_crc32={payload['raw_crc32']:08x}; "
            f"sha256={payload['sha256'][:16]}")


if __name__ == "__main__":
    main()
