#ifndef ASTRA_INPUT_MODIFIERS_H
#define ASTRA_INPUT_MODIFIERS_H

/** @file input_modifiers.h @brief Modifier bits carried by input events. */

#include <stdint.h>

#define ASTRA_INPUT_MOD_LEFT_CTRL   (UINT32_C(1) << 0)
#define ASTRA_INPUT_MOD_LEFT_SHIFT  (UINT32_C(1) << 1)
#define ASTRA_INPUT_MOD_LEFT_ALT    (UINT32_C(1) << 2)
#define ASTRA_INPUT_MOD_LEFT_GUI    (UINT32_C(1) << 3)
#define ASTRA_INPUT_MOD_RIGHT_CTRL  (UINT32_C(1) << 4)
#define ASTRA_INPUT_MOD_RIGHT_SHIFT (UINT32_C(1) << 5)
#define ASTRA_INPUT_MOD_RIGHT_ALT   (UINT32_C(1) << 6)
#define ASTRA_INPUT_MOD_RIGHT_GUI   (UINT32_C(1) << 7)
#define ASTRA_INPUT_MOD_CAPS_LOCK   (UINT32_C(1) << 8)

#define ASTRA_INPUT_MOD_CTRL \
    (ASTRA_INPUT_MOD_LEFT_CTRL | ASTRA_INPUT_MOD_RIGHT_CTRL)
#define ASTRA_INPUT_MOD_SHIFT \
    (ASTRA_INPUT_MOD_LEFT_SHIFT | ASTRA_INPUT_MOD_RIGHT_SHIFT)
#define ASTRA_INPUT_MOD_ALT \
    (ASTRA_INPUT_MOD_LEFT_ALT | ASTRA_INPUT_MOD_RIGHT_ALT)
#define ASTRA_INPUT_MOD_GUI \
    (ASTRA_INPUT_MOD_LEFT_GUI | ASTRA_INPUT_MOD_RIGHT_GUI)

#endif
