#ifndef ASTRA_TEXT_STYLE_H
#define ASTRA_TEXT_STYLE_H

/** @file text_style.h @brief Shared text-run and cell-style bits. */

#include <stdint.h>

enum {
    ASTRA_TEXT_STYLE_BOLD = UINT32_C(1) << 0,
    ASTRA_TEXT_STYLE_FAINT = UINT32_C(1) << 1,
    ASTRA_TEXT_STYLE_ITALIC = UINT32_C(1) << 2,
    ASTRA_TEXT_STYLE_UNDERLINE = UINT32_C(1) << 3,
    ASTRA_TEXT_STYLE_BLINK = UINT32_C(1) << 4,
    ASTRA_TEXT_STYLE_INVERSE = UINT32_C(1) << 5,
    ASTRA_TEXT_STYLE_HIDDEN = UINT32_C(1) << 6,
    ASTRA_TEXT_STYLE_STRIKETHROUGH = UINT32_C(1) << 7,
    ASTRA_TEXT_STYLE_ALLOWED_MASK = UINT32_C(0xff),
    ASTRA_TEXT_RENDER_STYLE_MASK =
        ASTRA_TEXT_STYLE_BOLD | ASTRA_TEXT_STYLE_ITALIC |
        ASTRA_TEXT_STYLE_UNDERLINE | ASTRA_TEXT_STYLE_STRIKETHROUGH
};

#endif
