[global]
   workgroup = WORKGROUP
   server string = Astra68
   netbios name = ASTRA68
   security = user
   map to guest = Bad User
   guest account = root
   create mask = 0664
   directory mask = 0775
   log level = 0

[astra]
   comment = Astra68 shared storage
   path = /data/astra/share
   browseable = yes
   read only = no
   guest ok = yes
   force user = root
