#!/usr/bin/env python3
"""Generate the Astra render v1 C and SystemVerilog protocol constants."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]
SPEC_PATH = Path(__file__).with_name("astra_render_v1.json")
C_PATH = ROOT / "fpga/arty/linux/astra_render_protocol.h"
SV_PATH = ROOT / "fpga/arty/graphics/astra_render_protocol.vh"
SCENE_C_PATH = ROOT / "sw/include/astra/window_scene_protocol.h"
SCENE_SV_PATH = ROOT / "fpga/arty/graphics/astra_window_scene_protocol.vh"


def constant_rows(spec: dict[str, object]) -> list[tuple[str, int]]:
    rows = [
        ("ABI_VERSION", int(spec["abi_version"])),
        ("COMMAND_BYTES", int(spec["command_bytes"])),
        ("COMPLETION_BYTES", int(spec["completion_bytes"])),
        ("SURFACE_DESCRIPTOR_BYTES", int(spec["surface_descriptor_bytes"])),
        ("GLYPH_DESCRIPTOR_BYTES", int(spec["glyph_descriptor_bytes"])),
        ("MAX_GLYPH_DESCRIPTORS", int(spec["max_glyph_descriptors"])),
        ("MAX_FILL_RECTS", int(spec["max_fill_rects"])),
        ("FILL_RECT_BYTES", int(spec["fill_rect_bytes"])),
        ("MAX_LINE_SEGMENTS", int(spec["max_line_segments"])),
        ("LINE_SEGMENT_BYTES", int(spec["line_segment_bytes"])),
        ("RING_ENTRIES", int(spec["ring_entries"])),
        ("MAX_DEADLINE_US", int(spec["max_deadline_us"])),
        ("MAX_SURFACE_DIMENSION", int(spec["max_surface_dimension"])),
        ("MAX_TRIANGLES", int(spec["max_triangles"])),
        ("TRIANGLE_VERTEX_BYTES", int(spec["triangle_vertex_bytes"])),
    ]
    for group, prefix in (
        ("host_aperture", "HOST_APERTURE"),
        ("formats", "FORMAT"),
        ("opcodes", "OP"),
        ("status", "STATUS"),
        ("surface_flags", "SURFACE"),
        ("command_flags", "FLAG"),
        ("geometry_flags", "GEOMETRY_FLAG"),
        ("glyph_flags", "GLYPH_FLAG"),
        ("glyph_options", "GLYPH_OPTION"),
        ("fill_rects_options", "FILL_RECTS_OPTION"),
        ("lines_options", "LINES_OPTION"),
        ("blit_rops", "ROP"),
        ("blit_options", "BLIT_OPTION"),
        ("command_word_offsets", "CMD_WORD"),
        ("geometry_word_offsets", "GEOMETRY_WORD"),
        ("flood_word_offsets", "FLOOD_WORD"),
        ("glyph_word_offsets", "GLYPH_WORD"),
        ("glyph_descriptor_word_offsets", "GLYPH_DESCRIPTOR_WORD"),
        ("fill_rects_word_offsets", "FILL_RECTS_WORD"),
        ("fill_rect_record_word_offsets", "FILL_RECT_WORD"),
        ("lines_word_offsets", "LINES_WORD"),
        ("line_segment_word_offsets", "LINE_SEGMENT_WORD"),
        ("surface_word_offsets", "SURFACE_WORD"),
        ("completion_word_offsets", "COMPLETION_WORD"),
        ("triangle_options", "TRIANGLE_OPTION"),
        ("triangle_word_offsets", "TRIANGLE_WORD"),
        ("triangle_vertex_word_offsets", "TRIANGLE_VERTEX_WORD"),
    ):
        values = spec[group]
        assert isinstance(values, dict)
        rows.extend((f"{prefix}_{name}", int(value))
                    for name, value in values.items())
    return rows


def render_c(rows: list[tuple[str, int]]) -> str:
    body = "\n".join(
        f"    ASTRA_RENDER_{name} = {value}u," for name, value in rows
    )
    return f"""// Generated by generate_protocol.py. Do not edit.
// SPDX-License-Identifier: MIT
#ifndef ASTRA_RENDER_PROTOCOL_H
#define ASTRA_RENDER_PROTOCOL_H

enum astra_render_protocol_constant {{
{body}
}};

#endif
"""


def render_sv(rows: list[tuple[str, int]]) -> str:
    body = "\n".join(
        f"`define ASTRA_RENDER_{name} {value}" for name, value in rows
    )
    return f"""// Generated by generate_protocol.py. Do not edit.
`ifndef ASTRA_RENDER_PROTOCOL_VH
`define ASTRA_RENDER_PROTOCOL_VH

{body}

`endif
"""


def render_scene_c(rows: list[tuple[str, int]]) -> str:
    body = "\n".join(
        f"#define ASTRA_WINDOW_SCENE_{name} UINT32_C({value})"
        for name, value in rows
    )
    return f"""// Generated by generate_protocol.py. Do not edit.
// SPDX-License-Identifier: MIT
#ifndef ASTRA_WINDOW_SCENE_PROTOCOL_H
#define ASTRA_WINDOW_SCENE_PROTOCOL_H

#include <stdint.h>

{body}

#endif
"""


def render_scene_sv(rows: list[tuple[str, int]]) -> str:
    body = "\n".join(
        f"`define ASTRA_WINDOW_SCENE_{name} {value}" for name, value in rows
    )
    return f"""// Generated by generate_protocol.py. Do not edit.
`ifndef ASTRA_WINDOW_SCENE_PROTOCOL_VH
`define ASTRA_WINDOW_SCENE_PROTOCOL_VH

{body}

`endif
"""


def update(path: Path, content: str, check: bool) -> bool:
    current = path.read_text() if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}")
        return False
    path.write_text(content)
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text())
    rows = constant_rows(spec)
    scene = spec["window_scene"]
    assert isinstance(scene, dict)
    scene_rows = [(name, int(value)) for name, value in scene.items()]
    valid = update(C_PATH, render_c(rows), args.check)
    valid &= update(SV_PATH, render_sv(rows), args.check)
    valid &= update(SCENE_C_PATH, render_scene_c(scene_rows), args.check)
    valid &= update(SCENE_SV_PATH, render_scene_sv(scene_rows), args.check)
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
