#ifndef ASTRA_INTERNAL_MEMORY_MAP_H
#define ASTRA_INTERNAL_MEMORY_MAP_H

#include <stdint.h>

/* Private hardware ABI. Applications must use the public NDK functions. */
#define ASTRA_HW_FRONT_PANEL_BASE UINT32_C(0xFFF01000)

#define ASTRA_HW_PANEL_ID            UINT32_C(0x00)
#define ASTRA_HW_PANEL_VERSION       UINT32_C(0x04)
#define ASTRA_HW_PANEL_CAPS          UINT32_C(0x08)
#define ASTRA_HW_PANEL_INPUT         UINT32_C(0x0C)
#define ASTRA_HW_PANEL_RAW_INPUT     UINT32_C(0x10)
#define ASTRA_HW_PANEL_CHANGE        UINT32_C(0x14)
#define ASTRA_HW_PANEL_LED_DATA      UINT32_C(0x18)
#define ASTRA_HW_PANEL_LED_OWNERSHIP UINT32_C(0x1C)
#define ASTRA_HW_PANEL_LED_SET       UINT32_C(0x20)
#define ASTRA_HW_PANEL_LED_CLEAR     UINT32_C(0x24)
#define ASTRA_HW_PANEL_LED_TOGGLE    UINT32_C(0x28)

#define ASTRA_HW_PANEL_ID_MAGIC UINT32_C(0x504E4C30) /* "PNL0" */
#define ASTRA_HW_PANEL_VERSION_1_0 UINT32_C(0x00010000)

#endif
