[workspace]
resolver = "3"
members = [
    "crates/astravm-app",
    "crates/astravm-machine",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MIT"

[workspace.dependencies]
eframe = { version = "0.35.0", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "x11",
] }
astravm-machine = { path = "crates/astravm-machine" }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"

