#!/usr/bin/env python3
"""Generate the Astra kernel build-identity header."""

import argparse
import datetime
import os
import pathlib
import subprocess


def git_output(repo: pathlib.Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def build_timestamp() -> str:
    source_epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if source_epoch is not None:
        now = datetime.datetime.fromtimestamp(
            int(source_epoch), datetime.timezone.utc
        )
    else:
        now = datetime.datetime.now(datetime.timezone.utc)
    return now.strftime("%Y-%m-%dT%H:%M:%SZ")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    repo = pathlib.Path(__file__).resolve().parents[2]
    revision = os.environ.get("ASTRA_KERNEL_GIT_REVISION")
    if not revision:
        commit = git_output(repo, "rev-parse", "HEAD") or "unknown"
        dirty = bool(
            git_output(repo, "status", "--porcelain", "--untracked-files=normal")
        )
        revision = commit + ("-dirty" if dirty else "")

    commit_prefix = revision.split("-", 1)[0][:8]
    try:
        revision_id = int(commit_prefix, 16)
    except ValueError:
        revision_id = 0

    content = f"""// Generated by gen_build_info.py. Do not edit.
#ifndef ASTRA_KERNEL_BUILD_INFO_H
#define ASTRA_KERNEL_BUILD_INFO_H

#define ASTRA_KERNEL_VERSION \"{args.version}\"
#define ASTRA_KERNEL_BUILD_UTC \"{build_timestamp()}\"
#define ASTRA_KERNEL_GIT_REVISION \"{revision}\"
#define ASTRA_KERNEL_REVISION_ID 0x{revision_id:08x}u

#endif
"""

    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text() != content:
        args.output.write_text(content)


if __name__ == "__main__":
    main()
