#ifndef ASTRA_KERNEL_QUALIFICATION_H
#define ASTRA_KERNEL_QUALIFICATION_H

/* Fixed inputs and shared-memory protocol for the packaged user image. */
#define KERNEL_QUALIFICATION_SHARED_BASE 0x70000000
#define KERNEL_QUALIFICATION_PHASE_OFFSET 4
#define KERNEL_QUALIFICATION_THREAD_HANDLE_OFFSET 8
#define KERNEL_QUALIFICATION_EVENT_HANDLE_OFFSET 12
#define KERNEL_QUALIFICATION_SEMAPHORE_HANDLE_OFFSET 16
#define KERNEL_QUALIFICATION_CLOSE_EVENT_HANDLE_OFFSET 20
#define KERNEL_QUALIFICATION_FINAL_EVENT_HANDLE_OFFSET 24

#define KERNEL_QUALIFICATION_PHASE_READY  0x52454144
#define KERNEL_QUALIFICATION_PHASE_CANCEL 0x43414e43
#define KERNEL_QUALIFICATION_PHASE_SEM    0x53454d41
#define KERNEL_QUALIFICATION_PHASE_CLOSE  0x434c4f53
#define KERNEL_QUALIFICATION_PHASE_FINAL  0x46494e4c
#define KERNEL_QUALIFICATION_PHASE_ERROR  0x45525221

#define KERNEL_QUALIFICATION_SYNC_RIGHTS 0x59
#define KERNEL_QUALIFICATION_TIMEOUT_NS 1000000
#define KERNEL_QUALIFICATION_QUANTUM_SPIN_ITERATIONS 32768

#endif
