#ifndef ASTRA_KERNEL_QUALIFICATION_H
#define ASTRA_KERNEL_QUALIFICATION_H

/*
 * Fixed inputs and shared-memory protocol for the packaged user image.
 *
 * The shared block is the process's data page, KERNEL_PROCESS_DATA_BASE,
 * spelled as a literal because the image is assembled and process.h is not
 * assembly. process.c asserts the two agree.
 */
#define KERNEL_QUALIFICATION_SHARED_BASE 0x00200000
#define KERNEL_QUALIFICATION_PHASE_OFFSET 4
#define KERNEL_QUALIFICATION_THREAD_HANDLE_OFFSET 8
#define KERNEL_QUALIFICATION_EVENT_HANDLE_OFFSET 12
#define KERNEL_QUALIFICATION_SEMAPHORE_HANDLE_OFFSET 16
#define KERNEL_QUALIFICATION_CLOSE_EVENT_HANDLE_OFFSET 20
#define KERNEL_QUALIFICATION_FINAL_EVENT_HANDLE_OFFSET 24
#define KERNEL_QUALIFICATION_K5_THREAD_HANDLE_OFFSET 28
#define KERNEL_QUALIFICATION_K5_RESULT_OFFSET 32
#define KERNEL_QUALIFICATION_K6_THREAD_HANDLE_OFFSET 36
#define KERNEL_QUALIFICATION_K6_RESULT_OFFSET 40
#define KERNEL_QUALIFICATION_K6_TIMER_RESULT_OFFSET 44
#define KERNEL_QUALIFICATION_K6_PROCESS_RESULT_OFFSET 48
#define KERNEL_QUALIFICATION_K7_RESULT_OFFSET 52
#define KERNEL_QUALIFICATION_K7_RECEIVE_HANDLE_OFFSET 56
#define KERNEL_QUALIFICATION_K7_SEND_HANDLE_OFFSET 60
#define KERNEL_QUALIFICATION_K7_EVENT_HANDLE_OFFSET 64
#define KERNEL_QUALIFICATION_K8_RESULT_OFFSET 68
#define KERNEL_QUALIFICATION_K8_AREA_HANDLE_OFFSET 72
#define KERNEL_QUALIFICATION_K8_AREA_BASE_OFFSET 76
#define KERNEL_QUALIFICATION_K8_PRODUCER_HANDLE_OFFSET 80
#define KERNEL_QUALIFICATION_K8_CONSUMER_HANDLE_OFFSET 84
#define KERNEL_QUALIFICATION_K8_THREAD_HANDLE_OFFSET 88
#define KERNEL_QUALIFICATION_K10_IRQ_RECORD_OFFSET 96
#define KERNEL_QUALIFICATION_K10_STORAGE_RESULT_OFFSET 112
#define KERNEL_QUALIFICATION_K10_INPUT_RESULT_OFFSET 116
#define KERNEL_QUALIFICATION_K10_VEGA_RESULT_OFFSET 120
#define KERNEL_QUALIFICATION_K10_USB_RESULT_OFFSET 124
#define KERNEL_QUALIFICATION_K10_ASTRAEA_RESULT_OFFSET 128
#define KERNEL_QUALIFICATION_K10_RESULT_OFFSET 132
#define KERNEL_QUALIFICATION_K10_SOURCE_MASK_OFFSET 136
/* The sources actually qualified, which is a subset of the mask above. */
#define KERNEL_QUALIFICATION_K10_QUALIFIED_MASK_OFFSET 140

#define KERNEL_QUALIFICATION_PHASE_READY  0x52454144
#define KERNEL_QUALIFICATION_PHASE_CANCEL 0x43414e43
#define KERNEL_QUALIFICATION_PHASE_SEM    0x53454d41
#define KERNEL_QUALIFICATION_PHASE_CLOSE  0x434c4f53
#define KERNEL_QUALIFICATION_PHASE_FINAL  0x46494e4c
#define KERNEL_QUALIFICATION_PHASE_ERROR  0x45525221

#define KERNEL_QUALIFICATION_SYNC_RIGHTS 0x59
#define KERNEL_QUALIFICATION_THREAD_RIGHTS 0x51
#define KERNEL_QUALIFICATION_THREAD_PRIORITY 16
#define KERNEL_QUALIFICATION_K6_THREAD_PRIORITY 15
#define KERNEL_QUALIFICATION_CODE_BASE 0x00100000
#define KERNEL_QUALIFICATION_K5_ARGUMENT 0x4b354152
#define KERNEL_QUALIFICATION_K5_EXIT_STATUS 0x89abcdef
#define KERNEL_QUALIFICATION_K5_RESULT 0x4b354f4b
#define KERNEL_QUALIFICATION_K6_ARGUMENT 0x4b364152
#define KERNEL_QUALIFICATION_K6_EXIT_STATUS 0x4b36584f
#define KERNEL_QUALIFICATION_K6_RESULT 0x4b364f4b
#define KERNEL_QUALIFICATION_K6_TIMER_RESULT 0x4b36544d
#define KERNEL_QUALIFICATION_K6_PROCESS_RESULT 0x4b365052
#define KERNEL_QUALIFICATION_K7_RESULT 0x4b374f4b
#define KERNEL_QUALIFICATION_K7_PROTOCOL 0x4b375450
#define KERNEL_QUALIFICATION_K7_TRANSACTION 0x12345678
#define KERNEL_QUALIFICATION_K7_MESSAGE_SIZE 32
#define KERNEL_QUALIFICATION_K7_EVENT_RIGHTS 0x79
#define KERNEL_QUALIFICATION_K8_ARGUMENT 0x4b384152
#define KERNEL_QUALIFICATION_K8_EXIT_STATUS 0x4b38584f
#define KERNEL_QUALIFICATION_K8_RESULT 0x4b384f4b
#define KERNEL_QUALIFICATION_K8_AREA_RIGHTS 0x67
#define KERNEL_QUALIFICATION_K8_AREA_REDUCED_RIGHTS 0x25
#define KERNEL_QUALIFICATION_K8_MAP_FLAGS 0x03
#define KERNEL_QUALIFICATION_K8_AREA_SIZE 4096
#define KERNEL_QUALIFICATION_K8_AREA_BASE 0x40000000
#define KERNEL_QUALIFICATION_K8_ELEMENT_SIZE 16
#define KERNEL_QUALIFICATION_K8_CAPACITY 4
#define KERNEL_QUALIFICATION_K8_TRANSFER_COUNT 2
#define KERNEL_QUALIFICATION_K8_TOTAL_SIZE 128
#define KERNEL_QUALIFICATION_K8_THREAD_PRIORITY 17
#define KERNEL_QUALIFICATION_COMMAND_MASK 0xffffff00
#define KERNEL_QUALIFICATION_COMMAND_PREFIX 0x4b100000
#define KERNEL_QUALIFICATION_COMMAND_QUERY_IRQS 0x4b100001
#define KERNEL_QUALIFICATION_COMMAND_BIND_IRQ 0x4b100002
#define KERNEL_QUALIFICATION_COMMAND_PREPARE_IRQ 0x4b100003
#define KERNEL_QUALIFICATION_COMMAND_CONSUME_IRQ 0x4b100004
#define KERNEL_QUALIFICATION_COMMAND_COMPLETE_IRQS 0x4b100005

#define KERNEL_QUALIFICATION_IRQ_STORAGE 4
#define KERNEL_QUALIFICATION_IRQ_INPUT 5
#define KERNEL_QUALIFICATION_IRQ_USB 7
#define KERNEL_QUALIFICATION_IRQ_VEGA 8
#define KERNEL_QUALIFICATION_IRQ_ASTRAEA 9
#define KERNEL_QUALIFICATION_IRQ_BIT(source) (1 << (source))
#define KERNEL_QUALIFICATION_IRQ_SOURCE_MASK 0x000003b0

#define KERNEL_QUALIFICATION_IRQ_STORAGE_EXPECTED 0x80000000
#define KERNEL_QUALIFICATION_IRQ_INPUT_EXPECTED 0x00000100
#define KERNEL_QUALIFICATION_IRQ_USB_EXPECTED 0x20000004
#define KERNEL_QUALIFICATION_IRQ_VEGA_EXPECTED 0x00000001
#define KERNEL_QUALIFICATION_IRQ_ASTRAEA_EXPECTED 0x00000001
/*
 * What a process killed by its own fault reports to a death waiter. It is
 * ASTRA_STATUS_FAULTED, not zero: the kernel substitutes the verdict at the
 * one point every process leaves through, because zero is what a program says
 * when it succeeded. The harness asserted zero here and died on it.
 * process.c asserts this literal still matches the header.
 */
#define KERNEL_QUALIFICATION_OFFENDER_EXIT_STATUS 0x80000001
#define KERNEL_QUALIFICATION_K10_SOURCE_RESULT 0x4b104f4b
#define KERNEL_QUALIFICATION_K10_RESULT 0x4b31304b

/* One real AstraHost-SPI event identifies each runtime link generation. */
#define KERNEL_QUALIFICATION_INPUT_CLASS 0x7e
#define KERNEL_QUALIFICATION_INPUT_KIND 0x01
#define KERNEL_QUALIFICATION_INPUT_FLAGS 0x4b10
#define KERNEL_QUALIFICATION_INPUT_VALUE 0x41535452
#define KERNEL_QUALIFICATION_INPUT_DEVICE 0x4b10
#define KERNEL_QUALIFICATION_TIMEOUT_NS 1000000
#define KERNEL_QUALIFICATION_K6_TIMEOUT_NS 20000000
#define KERNEL_QUALIFICATION_K6_TIMER_NS 2000000
/*
 * How long the survivor and the offender stay runnable together, doing
 * nothing but burning time at the same priority. The milestone asserts a
 * quantum preemption happened, and only two co-runnable threads of equal
 * priority can produce one; the quantum is 5 ms, so this is two of them and a
 * margin. It is a duration rather than an iteration count because the count
 * that lasted a quantum on a 30 MHz 68030 lasts a fraction of one under an
 * emulator, and the preemption then never happens.
 */
#define KERNEL_QUALIFICATION_QUANTUM_SPIN_NS 12000000

#endif
