#ifndef ASTRA_KERNEL_QUALIFICATION_H
#define ASTRA_KERNEL_QUALIFICATION_H

/* Kernel-internal calls used only by the packaged qualification image. */
#define KERNEL_QUALIFICATION_EVENT_WAIT   0x7f000001
#define KERNEL_QUALIFICATION_EVENT_SIGNAL 0x7f000002
#define KERNEL_QUALIFICATION_EVENT_WAIT_TIMEOUT 0x7f000003
#define KERNEL_QUALIFICATION_TIMEOUT_CYCLES 12500
#define KERNEL_QUALIFICATION_QUANTUM_SPIN_ITERATIONS 32768

#endif
