// SPDX-License-Identifier: MIT
#ifndef ASTRA_DISPLAY_CAPTURE_H
#define ASTRA_DISPLAY_CAPTURE_H

/* Final physical-display capture protocol shared by hardware and host code. */
#define ASTRA_DISPLAY_CAPTURE_WIDTH 1920u
#define ASTRA_DISPLAY_CAPTURE_HEIGHT 1080u
#define ASTRA_DISPLAY_CAPTURE_PIXEL_BYTES 3u
#define ASTRA_DISPLAY_CAPTURE_FRAME_BYTES \
    (ASTRA_DISPLAY_CAPTURE_WIDTH * ASTRA_DISPLAY_CAPTURE_HEIGHT * \
     ASTRA_DISPLAY_CAPTURE_PIXEL_BYTES)
#define ASTRA_DISPLAY_CAPTURE_ALIGNMENT 256u
#define ASTRA_DISPLAY_CAPTURE_DEVICE_ID 0x41434150u
#define ASTRA_DISPLAY_CAPTURE_VERSION 0x00010000u

#define ASTRA_CAPTURE_REG_DEVICE_ID 0x00u
#define ASTRA_CAPTURE_REG_VERSION 0x04u
#define ASTRA_CAPTURE_REG_CAPABILITIES 0x08u
#define ASTRA_CAPTURE_REG_CONTROL 0x0cu
#define ASTRA_CAPTURE_REG_STATUS 0x10u
#define ASTRA_CAPTURE_REG_BUFFER_BASE 0x14u
#define ASTRA_CAPTURE_REG_FRAME_BYTES 0x18u
#define ASTRA_CAPTURE_REG_COMPLETED_BASE 0x1cu
#define ASTRA_CAPTURE_REG_COMPLETED_GENERATION 0x20u
#define ASTRA_CAPTURE_REG_COMPLETED_COUNT 0x24u
#define ASTRA_CAPTURE_REG_DROPPED_COUNT 0x28u
#define ASTRA_CAPTURE_REG_OVERFLOW_COUNT 0x2cu
#define ASTRA_CAPTURE_REG_AXI_ERROR_COUNT 0x30u
#define ASTRA_CAPTURE_REG_COMMAND_ERROR_COUNT 0x34u
#define ASTRA_CAPTURE_REG_LAST_CYCLES 0x38u
#define ASTRA_CAPTURE_REGISTER_BYTES 0x3cu

#define ASTRA_CAPTURE_ENABLE (1u << 0)
#define ASTRA_CAPTURE_ARM (1u << 1)
#define ASTRA_CAPTURE_ACKNOWLEDGE (1u << 2)
#define ASTRA_CAPTURE_CLEAR_COUNTERS (1u << 3)

#define ASTRA_CAPTURE_STATUS_ENABLED (1u << 0)
#define ASTRA_CAPTURE_STATUS_ARMED (1u << 1)
#define ASTRA_CAPTURE_STATUS_ACTIVE (1u << 2)
#define ASTRA_CAPTURE_STATUS_COMPLETE (1u << 3)
#define ASTRA_CAPTURE_STATUS_WRITER_BUSY (1u << 4)
#define ASTRA_CAPTURE_STATUS_FRAME_DONE (1u << 5)
#define ASTRA_CAPTURE_STATUS_FIFO_OVERFLOW (1u << 6)
#define ASTRA_CAPTURE_STATUS_LAST_DROPPED (1u << 7)
#define ASTRA_CAPTURE_STATUS_LAST_AXI_ERROR (1u << 8)
#define ASTRA_CAPTURE_STATUS_COMMAND_ERROR (1u << 9)

#define ASTRA_CAPTURE_STATUS_ERROR_MASK \
    (ASTRA_CAPTURE_STATUS_FIFO_OVERFLOW | \
     ASTRA_CAPTURE_STATUS_LAST_DROPPED | \
     ASTRA_CAPTURE_STATUS_LAST_AXI_ERROR | \
     ASTRA_CAPTURE_STATUS_COMMAND_ERROR)

#endif
