#ifndef ASTRA_SYSCALL_H
#define ASTRA_SYSCALL_H

#define ASTRA_SYSCALL_TRAP 15
#define ASTRA_SYSCALL_VECTOR 47
#define ASTRA_SYSCALL_ABI_VERSION 0x00010000

#define ASTRA_SYSCALL_QUERY_ABI 0
#define ASTRA_SYSCALL_PROGRESS  1
#define ASTRA_SYSCALL_YIELD     2
#define ASTRA_SYSCALL_EXIT      3
#define ASTRA_SYSCALL_CLOSE     4

#define ASTRA_SYSCALL_OK               0
#define ASTRA_SYSCALL_BAD_SYSCALL      1
#define ASTRA_SYSCALL_INVALID_ARGUMENT 2
#define ASTRA_SYSCALL_INVALID_HANDLE   3
#define ASTRA_SYSCALL_ACCESS_DENIED    4

#endif
