#ifndef ASTRA_SYSCALL_H
#define ASTRA_SYSCALL_H

#define ASTRA_SYSCALL_TRAP 15
#define ASTRA_SYSCALL_VECTOR 47
#define ASTRA_SYSCALL_ABI_VERSION 0x00010000

#define ASTRA_SYSCALL_QUERY_ABI 0
#define ASTRA_SYSCALL_PROGRESS  1
#define ASTRA_SYSCALL_YIELD     2
#define ASTRA_SYSCALL_EXIT      3
#define ASTRA_SYSCALL_CLOSE     4
#define ASTRA_SYSCALL_CLOCK_MONOTONIC  5
#define ASTRA_SYSCALL_EVENT_CREATE     6
#define ASTRA_SYSCALL_SEMAPHORE_CREATE 7
#define ASTRA_SYSCALL_WAIT_ONE         8
#define ASTRA_SYSCALL_SIGNAL           9
#define ASTRA_SYSCALL_EVENT_RESET      10
#define ASTRA_SYSCALL_CANCEL_WAIT      11

#define ASTRA_SYSCALL_OK               0
#define ASTRA_SYSCALL_BAD_SYSCALL      1
#define ASTRA_SYSCALL_INVALID_ARGUMENT 2
#define ASTRA_SYSCALL_INVALID_HANDLE   3
#define ASTRA_SYSCALL_ACCESS_DENIED    4
#define ASTRA_SYSCALL_RESOURCE_LIMIT   5
#define ASTRA_SYSCALL_WOULD_BLOCK      6
#define ASTRA_SYSCALL_TIMED_OUT        7
#define ASTRA_SYSCALL_PEER_DEAD        8
#define ASTRA_SYSCALL_BAD_ADDRESS      9
#define ASTRA_SYSCALL_CANCELLED        10
#define ASTRA_SYSCALL_OUT_OF_MEMORY    11
#define ASTRA_SYSCALL_IO_ERROR         12
#define ASTRA_SYSCALL_CLOSED           13

#ifndef ASTRA_RIGHTS_DEFINED
#define ASTRA_RIGHTS_DEFINED 1
#define ASTRA_RIGHT_READ       (1u << 0)
#define ASTRA_RIGHT_WRITE      (1u << 1)
#define ASTRA_RIGHT_MAP        (1u << 2)
#define ASTRA_RIGHT_SIGNAL     (1u << 3)
#define ASTRA_RIGHT_WAIT       (1u << 4)
#define ASTRA_RIGHT_TRANSFER   (1u << 5)
#define ASTRA_RIGHT_ADMINISTER (1u << 6)
#define ASTRA_RIGHT_DEBUG      (1u << 7)
#endif

#define ASTRA_EVENT_MANUAL_RESET       (1u << 0)
#define ASTRA_EVENT_INITIALLY_SIGNALED (1u << 1)

#define ASTRA_DEADLINE_NONE_HI 0x7fffffffu
#define ASTRA_DEADLINE_NONE_LO 0xffffffffu

#endif
