#!/bin/sh
# Build Astra's shared C++ runtime input from GCC's configured libstdc++ tree.
#
# Usage: build-libstdcxx-shared-archive.sh LIBSTDCXX_BUILD_DIR [CROSS_PREFIX]
#
# A GCC configured with --disable-shared intentionally builds libstdc++.a
# without PIC. That archive is correct for static executables, but embedding
# it in cxx.library creates text relocations. Rewriting finished objects would
# be brittle, and maintaining a private source list would duplicate upstream
# policy. Instead, reproduce GCC's configured build in an isolated sibling
# directory and ask its own makefiles to compile the same sources as PIC.

set -eu

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "usage: $0 LIBSTDCXX_BUILD_DIR [CROSS_PREFIX]" >&2
    exit 2
fi

build_dir=$1
cross=${2:-m68k-astra-}
cxx=${cross}g++

test -f "$build_dir/Makefile" || {
    echo "$0: not a configured libstdc++ build directory: $build_dir" >&2
    exit 1
}
test -f "$build_dir/config.cache" || {
    echo "$0: missing GCC cross-configuration cache: $build_dir/config.cache" >&2
    exit 1
}
test -x "$build_dir/config.status" || {
    echo "$0: missing executable config.status: $build_dir/config.status" >&2
    exit 1
}
test "$("$cxx" -dumpmachine)" = m68k-astra || {
    echo "$0: $cxx does not target m68k-astra" >&2
    exit 1
}

srcdir=$(sed -n 's/^srcdir = //p' "$build_dir/Makefile")
test -n "$srcdir" || {
    echo "$0: cannot determine libstdc++ source directory" >&2
    exit 1
}
srcdir=$(CDPATH= cd -- "$build_dir/$srcdir" && pwd)
configure=$srcdir/configure
test -x "$configure" || {
    echo "$0: missing libstdc++ configure script: $configure" >&2
    exit 1
}

parent=$(CDPATH= cd -- "$build_dir/.." && pwd)
name=$(basename "$build_dir")
pic_build=$parent/$name-astra-pic
case "$pic_build" in
    "$parent"/*-astra-pic) ;;
    *)
        echo "$0: refusing unsafe PIC build path: $pic_build" >&2
        exit 1
        ;;
esac

# config.status emits shell-quoted arguments, including compiler commands with
# spaces. It is generated by the trusted GCC configure step and is the sole
# authority for reproducing that target configuration.
config_args=$("$build_dir/config.status" --config)

rm -rf "$pic_build"
mkdir -p "$pic_build"
cp "$build_dir/config.cache" "$pic_build/config.cache"
(
    cd "$pic_build"
    eval "set -- $config_args"
    LDFLAGS= CPPFLAGS= "$configure" "$@"
)

jobs=${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1)}
make -C "$pic_build" -j "$jobs" \
    CFLAGS='-g -O2 -fPIC -ftls-model=initial-exec' \
    CXXFLAGS='-g -O2 -fPIC -ftls-model=initial-exec' all

archive=$pic_build/src/.libs/libstdc++.a
test -f "$archive" || {
    echo "$0: upstream build did not produce $archive" >&2
    exit 1
}

installed=$("$cxx" -print-file-name=libstdc++.a)
install_dir=$(dirname "$installed")
temporary=$install_dir/.libstdc++_shared.a.tmp.$$
trap 'rm -f "$temporary"' EXIT HUP INT TERM
cp "$archive" "$temporary"
mv "$temporary" "$install_dir/libstdc++_shared.a"
trap - EXIT HUP INT TERM

echo "installed $install_dir/libstdc++_shared.a"
